config/routes.rb
Rails.application.routes.draw do
  resources :snippets
  resources :kinds

  root "snippets#index"

end

app/models/kind.rb
class Kind < ActiveRecord::Base
  has_many :snippets, dependent: :nullify

  validates :name, presence: true,
                uniqueness: true
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :kind

  validates :title, presence: true,
                    uniqueness: true
  validates :work, presence: :true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController

  def new
    @kind = Kind.new
    render :new
  end

  def create
    @kind = Kind.new kind_params
    if @kind.save
      redirect_to kind_path(@kind), notice: "New Kind created!"
    else
      flash[:alert] = "ERROR: Kind not created"
      render :new
    end
  end

  def show
    find_kind
    render :show
  end

  def index
    @kinds = Kind.all
    render :index
  end

  def edit
    find_kind
    render :edit
  end

  def update
    find_kind
    if @kind.update kind_params
    redirect_to kind_path(@kind), notice: "Kind updated!"
  else
    flash[:alert] = "ERROR: Kind was not updated"
    render :edit
  end

  end


  private

  def kind_params
    params.require(:kind).permit(:name)
  end

  def find_kind
    @kind = Kind.find params[:id]
  end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :find_snippet, only: [:show, :edit, :update]
  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new snippet_params
    if @snippet.save
      redirect_to snippet_path(@snippet), notice: "Snippet created"
    else
      flash[:alert] = "Error: Snippet was not created"
      render :new
    end
  end

  def show
    render :show
  end

  def index
    @snippets = Snippet.all
  end

  def edit
    render :edit
  end

  def update
    if @snippet.update snippet_params
      redirect_to snippet_path(@snippet), notice: "Snippet Updated!"
    else
      flash[:alert] = "Error: Snippet was not updated!"
      render :edit
    end
  end

  private

  def snippet_params
    params.require(:snippet).permit(:title, :work)
  end

  def find_snippet
    @snippet = Snippet.find  params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/kinds/edit.html.erb
<h1>Edit a Kind</h1>

app/views/kinds/index.html.erb
<h1>Snippets by Kind</h1>

<%= link_to "Create a new Kind", new_kind_path %>

<% @kinds.each do |kind| %>
<%= link_to kind.name, kind_path(kind) %>
<% end %>

app/views/kinds/new.html.erb
<h1>Create a new kind to store snippets</h1>

<%= form_for @kind do |f| %>
  <%= f.label "Kind:" %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snippets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<!-- navigation -->

<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= snippets_path %>">Snippets</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "New Snippet", new_snippet_path %></li>
        <li><%= link_to "All Snippets", snippets_path  %></li>
        <li><%= link_to "Snippets by Kind", kinds_path  %></li>
      </ul>
    </div>
  </div>
</nav>


<!-- end of navigation -->
<%= yield %>

</body>
</html>

app/views/snippets/index.html.erb
<h1>All Snippets</h1>

<% @snippets.each do |snippet| %>
<%= link_to snippet.title, snippet_path(snippet) %>
  <br>
<% end %>

app/views/snippets/new.html.erb
<h1>Create New Snippet</h1>

<%= form_for @snippet do |f| %>
  <div class="">
    Kind: <%=  f.collection_select(:kind_id, Kind.all, :id, :name)%>
  </div>
  <br>
  <div class="">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="">
    <%= f.label :work %>
    <%= f.text_area :work, cols: 40, rows: 30 %>
  </div>
  <%= f.submit %>
<% end %>

app/views/snippets/show.html.erb
<h1><%= @snippet.title %></h1>
<br>
<%= @snippet.kind.name%>
<br>
<%= @snippet.work %>